### ISSUE TITLE
Doesn't Work Running Server in Docker Container

### ISSUE THREAD

**Issue by xanderdunn** [ajvondrak/remote_ip#6]
Here is the diff when I use RemoteIP:
```
--- a/lib/endpoint.ex
+++ b/lib/endpoint.ex
@@ -10,6 +10,9 @@ defmodule APITournament.Endpoint do
   use Absinthe.Phoenix.Endpoint
   use Plug.ErrorHandler
   use Sentry.Plug
+  use Plug.Builder
+  plug RemoteIP

   socket "/sock", APITournament.MainSocket

--- a/mix.exs
+++ b/mix.exs
@@ -89,6 +89,7 @@ defmodule APITournament.Mixfile do
       {:sentry,           "~> 6.0.0"},
       {:ip2country,       "~> 1.1"},
+      {:remote_ip,        "~> 0.1.0"},
     ]
   end
```

I then build the Docker image and run it locally with port 4000 exposed and query it using curl with a forwarded IP header:
```
docker build -t api-tournament .
sudo docker run -p 4000:4000 -it api-tournament
curl --header "X-Forwarded-For: 192.168.0.2" http://localhost:4000/
```
Here is the output I get when I execute the curl command:
```
# conn.req_headers
[{"host", "localhost:4000"}, {"user-agent", "curl/7.52.1"}, {"accept", "*/*"},
 {"x-forwarded-for", "192.168.0.2"}]
# conn.remote_ip
{0, 0, 0, 0, 0, 65535, 44049, 1}
# to_string(:inet_parse.ntoa(conn.remote_ip))
::ffff:172.17.0.1
```

Here is the diff when I use [plug_forwarded_peer](https://github.com/kbrw/plug_forwarded_peer):
```
--- a/lib/endpoint.ex
+++ b/lib/endpoint.ex
@@ -10,6 +10,9 @@ defmodule APITournament.Endpoint do
   use Absinthe.Phoenix.Endpoint
   use Plug.ErrorHandler
   use Sentry.Plug
+  use Plug.Builder
+  plug PlugForwardedPeer

   socket "/sock", APITournament.MainSocket

--- a/mix.exs
+++ b/mix.exs
@@ -89,6 +89,7 @@ defmodule APITournament.Mixfile do
       {:sentry,           "~> 6.0.0"},
       {:ip2country,       "~> 1.1"},
       {:remote_ip,        "~> 0.1.0"},
+      {:plug_forwarded_peer, "~> 0.0.2"},
     ]
   end
```

Using the same docker build and curl:
```
[info] GET /
# conn.req_headers
[{"host", "localhost:4000"}, {"user-agent", "curl/7.52.1"}, {"accept", "*/*"},
 {"x-forwarded-for", "192.168.0.2"}]
# conn.remote_ip
{192, 168, 0, 2}
# to_string(:inet_parse.ntoa(conn.remote_ip))
192.168.0.2
```

This is the correct output, but I can't figure out why it appears RemoteIP does nothing with the `x-forwarded-for` header when it's present.

**Comment by ajvondrak** [comment]
Check out the [Algorithm in the README](https://github.com/ajvondrak/remote_ip#algorithm), particularly the part about computing the IP.

Not only is your header a 192.168.0.0/16 address (which is implicitly ignored), but you also only have a single hop (the plug assumes you have at least one proxy, so trusts the rightmost header implicitly). So we ultimately resolve that the "call is coming from inside the house". [This behavior is codified in the tests.](https://github.com/ajvondrak/remote_ip/blob/827762a087cd10b897ef7a4ad1d8c2c7c5a7301f/test/remote_ip_test.exs#L52-L57)

**Comment by xanderdunn** [comment]
Thanks.  I'm not very experienced in networking, so any help is appreciated.  

When I have remote_ip running in my production setup, I get the same results:
Cloudflare Proxy -> AWS Load Balancer -> AWS EC2 instance -> Phoenix server running inside a Docker container

In that situation, `conn.remote_ip` is still `{0, 0, 0, 0, 0, 65535, 44049, 1}`.  The call is certainly not coming from within the house there, so I wouldn't expect this behavior.  Do you have ideas on why this might be?

**Comment by ajvondrak** [comment]
I'd log your headers in production to see what they come in as; from there, it's pretty straightforward to trace what the RemoteIp algorithm actually does. Whether it's _correct_ for your application is another matter, of course. :)

I apparently hit the "close and comment" button before, which may have been hasty if indeed there's something RemoteIp should be doing differently. Wouldn't necessarily rule that out; it's been a long time since I've looked at this code. But getting some data would certainly help figure out if that's the case.

Since you mention them, I do recall that there was a specific plug for Cloudflare: https://github.com/c-rack/plug_cloudflare It looks like it does two things that could still be accomplished by RemoteIp:

* checks the custom `CF-Connecting-IP` header; this is an easy config option in RemoteIp
* validates trusted Cloudflare IPs; also an option for RemoteIp, modulo some plumbing to hit their API for the list of IPs

That said, [the Cloudflare docs](https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-) seem to indicate that they'll also append to the `X-Forwarded-For` header. Might be worth verifying the values of both headers in your setup.

I'm not well-versed in Docker, so I don't know if their port-forwarding is doing anything crazy. My initial instinct is that it's a red herring, but what do I know? Might see what you can log at each layer: see if the headers look different coming into your EC2 versus into your Phoenix server in the Docker image. Debug print statements all the way down! Haha.

**Comment by acrogenesis** [comment]
I had a similar error to this. My setup is a bit differente Cloudflare -> kubernetes (with argo-tunnel) -> pod (docker)

I just had to add the kubernetes local ip's to the proxy list for it to work, I assume it would be the same with your EC2 instance.

My plug configuration ended up like this:

```
plug(RemoteIp,
    headers: ~w(forwarded x-forwarded-for x-client-ip x-real-ip cf-connecting-ip),
    proxies:
      ~w(10.224.0.0/24 f00d::af3:0:0:0/96 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 104.16.0.0/12 108.162.192.0/18 131.0.72.0/22 141.101.64.0/18 162.158.0.0/15 172.64.0.0/13 173.245.48.0/20 188.114.96.0/20 190.93.240.0/20 197.234.240.0/22 198.41.128.0/17 2400:cb00::/32 2405:b500::/32 2606:4700::/32 2803:f800::/32 2c0f:f248::/32 2a06:98c0::/29)
  )
```
the first two cidr are of k8s and the rest are cloudflares ips

**Comment by ajvondrak** [comment]
As mentioned in the [commit message](https://github.com/ajvondrak/remote_ip/commit/375bf743106294e5a2b52cade225cda629c55414), I added debug logging that should help troubleshoot issues like this. For lack of activity in the meantime, I'm going to go ahead and close this specific issue.
